### PR TITLE
Link to setup-arduino-cli examples.

### PR DESCRIPTION
**Pull request by ArminJo**
2 weeks ago I needed a script for test compiling of my Arduino libraries. But I could not find any example around.

So I have to build it by my own, based on your awesome setup-arduino-cli, which took me a few days.

Now I would like to share my result and the best place I guess, is at your repository.
Therefore I added a link to the script in your README.md file.

I would appreciate if you can merge this pull request.
Please tell me if I should change the wording of the, this was a first guess.

Regards
Armin

### CODE REVIEW

**Comment by per1234** [comment]
The `setup-arduino-cli` action [has been moved](https://github.com/arduino/actions/pull/5/files) to https://github.com/arduino/setup-arduino-cli. A copy is only retained in this repository to avoid breaking workflows that were set up to use this repository's copy before the move.

You might be interested in our `arduino/libraries/compile-examples` action:
https://github.com/arduino/actions/tree/master/libraries/compile-examples

**Comment by ArminJo** [comment]
Hi per1234,
1. There no remark about the moving of the action. If you look for actions on GitHub https://github.com/marketplace/actions/setup-arduino-cli , this repo here ist linked. Maybe you can correct this.
2. I know the compile example, but I have to confess using Docker was not what I want, and I looked for an workflow capable of building for multiple boards like the [Adafruit script](https://github.com/adafruit/ci-arduino).
3. I want to help people in the same situation I was and like to share my results with the community. If you do not find it sensible to put a link here, maybe you have a better idea, I am not the pro regarding sharing results.

Thanks
Armin

**Comment by per1234** [comment]
>There no remark about the moving of the action

It's here:
https://github.com/arduino/actions/blob/master/setup-arduino-cli/README.md
>### Deprecated
>
>Please use https://github.com/arduino/setup-arduino-cli

---
>If you look for actions on GitHub https://github.com/marketplace/actions/setup-arduino-cli , this repo here ist linked. Maybe you can correct this.

I would like to fix that, but I can't find the link. Would you mind pointing me to exactly where that link is.

---
>I looked for an workflow capable of building for multiple boards

You can do that by setting up a matrix for the `fqbn` matrix. Here's an example workflow that compiles for all the MKR boards:
https://github.com/arduino-libraries/Arduino_MKRMEM/blob/master/.github/workflows/compile-examples.yml

But of course your approach is very nice too. I just thought you might be interested in Arduino's take on things. I have [my own CI script](https://github.com/per1234/arduino-ci-script) that I'm partial to.

---
>I want to help people in the same situation I was and like to share my results with the community.

Thanks! That spirit is a big part of what makes the Arduino community so awesome.

---
>If you do not find it sensible to put a link here, maybe you have a better idea, I am not the pro regarding sharing results.

I don't think it's a good idea to add any additional documentation for the setup-arduino-cli action to this repository, only because that action doesn't really live here any more. That's just my own opinion though. I'm not the person who decides what gets merged or not, both here and in the other repository.

**Comment by ArminJo** [comment]
Hi,
You should definitly put the [action](https://github.com/per1234/actions/tree/master/libraries/compile-examples) to the GitHub [marketplace](https://github.com/marketplace/new). Together with a link to some examples you have.
It would have saved me much effort If I had found it earlier, but it was buried down in libraries!!!
And maybe this is the place to change the link.

And you are right, It makes no sense to put links to examples here, they should be collected in the repo(s) you find linked in the marketplace when you search for "arduino"

**Pull request closed without merging**
